### ISSUE TITLE
Heading is ignored/removed

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#127]
I do notice that Facebook only accept `<h1>` and `<h2>`. I am so happy that the plugin have handle it by converting `<h3> `to `<h2>`. 

In the RSS feed, the plugin have handled nicely. But just realised that the `<h3>` was removed from the IA when it connect using Facebook SDK/ API method. 

Website
<img width="784" alt="screen shot 2016-04-13 at 7 52 33 pm" src="https://cloud.githubusercontent.com/assets/4049250/14492380/69289250-01b1-11e6-9020-18bb96dc16b7.png">

Facebook Instant Article
![13016608_10153664748634492_314439751_o](https://cloud.githubusercontent.com/assets/4049250/14492386/73b54dda-01b1-11e6-91d3-c74e35e9c199.jpg)

Or did I miss out something?

**Comment by diegoquinteiro** [comment]
Hi, @CarsonLee27,

Thanks for the feedback!

Can you try resubmitting your article?

The RSS output is generated using the same method as the article sent via API, so that should fix it.

Let me know if it worked.

**Comment by CarsonLee27** [comment]
@diegoquinteiro still the same =( Not sure why. Can u help me go though once at the RSS feed? Maybe there is some potential trigger issue? 

I notice the image source was converted to random code. Wondering izzit this caused the issue. 
http://tantannews.com/instant-articles/

Appreciate

**Comment by demoive** [comment]
@CarsonLee27, if there are problems with the filenames of images which contain non-roman characters, this has been reported in issue #148 so we'll close out this issue to avoid duplicates. Please follow that issue and share any additional information you feel would be helpful.

**Comment by CarsonLee27** [comment]
FYI, the issue seem resolved over here. Anyway, thanks =
