### ISSUE TITLE
Images with captions are not displaying in the articles

### ISSUE THREAD

**Issue by mikemacnn** [Automattic/facebook-instant-articles-wp#388]
# Steps required to reproduce the problem

1. Publish an article with an image in caption 

# Expected Result

Show image with caption

# Actual Result

Image with caption does not show

---

** Version Info **

* Plugin version: Version 3.0.1
* WordPress version: Version 4.5.3
* PHP version:

**Comment by everton-rosario** [comment]
Hello, @mikemacnn. 
Do you have an Image within the caption segment of another image?

Please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Closing until receiving more info, then I'll reopen.

**Comment by mikemacnn** [comment]
No rules defined for <div class="wp-caption alignnone"> in the context of InstantArticle
No rules defined for <div class="wp-caption alignnone"> in the context of InstantArticle



**source markup**


> <p>Even as Tesla&#8217;s Auto Pilot driver assist system is under scrutiny following the <a href="https://www.rushlane.com/tesla-model-s-autopilot-fatal-accident-12199962.html" target="_blank">Model S&#8217; fatal crash</a> in the US, the drive assist system has proved its worthiness by saving a Tesla Model X owner from a potentially life-threatening medical emergency.</p>
> <p>Joshua Neally, a resident of Springfield, Missouri, was driving back from his office when he suffered from pulmonary embolism, a condition of obstruction of blood vessels in the lungs which could potentially be fatal.</p>
> <div id="attachment_158998" style="width: 1435px" class="wp-caption alignnone"><a href="https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0.jpg" target="_blank"><img class="wp-image-158998 size-full" title="Tesla Autopilot 7.0" src="https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0.jpg" alt="Tesla Autopilot 7.0" width="1425" height="555" srcset="https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0.jpg 1425w, https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0-400x156.jpg 400w, https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0-600x234.jpg 600w, https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0-810x315.jpg 810w, https://www.rushlane.com/wp-content/uploads/2015/08/Tesla-Autopilot-7.0-1140x444.jpg 1140w" sizes="(max-width: 1425px) 100vw, 1425px" /></a>
> <p class="wp-caption-text">Auto Pilot can change lanes and react to traffic conditions automatically.</p>
> </div>
> <p>&nbsp;</p>
> <p>Neally experienced a piercing pain in his stomach and chest. Instead of parking his car and waiting for the ambulance to arrive, he made a quick decision to leave his fate in the hands of his electric crossover&#8217;s Auto Pilot system. He commanded his car&#8217;s Auto Pilot mode to take him to the nearest hospital.</p>
> <p>Roughly 20 miles (32 km) later, the Model X took Neally to a road leading to a hospital&#8217;s emergency department. He then parked the car manually and checked himself into the hospital. Now the owner is out of danger but the doctors say that he was lucky to survive the health scare while driving.</p>
> <div id="attachment_188503" style="width: 1290px" class="wp-caption alignnone"><a href="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4.jpg" target="_blank"><img class="wp-image-188503 size-full" title="Tesla Model X 2016 Geneva Motor Show" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4.jpg" alt="Tesla Model X 2016 Geneva Motor Show" width="1280" height="854" srcset="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4.jpg 1280w, https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-400x267.jpg 400w, https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-768x512.jpg 768w, https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-600x400.jpg 600w, https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-810x540.jpg 810w, https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-1140x761.jpg 1140w" sizes="(max-width: 1280px) 100vw, 1280px" /></a>
> <p class="wp-caption-text">Tesla&#8217;s Auto Pilot system is currently under investigation by NHTSA after a fatal crash.</p>
> </div>
> <p>Obviously, Joshua Neally is extremely happy about his car&#8217;s semi-autonomous capabilities that helped him receive medical attention as quick as possible.</p>
> <p style="text-align: center;"><strong>Also read &#8211; <a href="https://www.rushlane.com/man-hacks-tesla-model-s-pokemon-12201806.html" target="_blank">Man hacks Tesla Model S touchscreen to play Pokemon Go</a></strong></p>
> <p>Reacting to accidents that were caused by alleged malfunctioning of Auto Pilot, Tesla Motors earlier stated that drivers are ultimately responsible for the vehicle&#8217;s actions and the system only aims to eliminate driver errors. Neally&#8217;s experience adds gravity to Tesla&#8217;s claim that the Auto Pilot helps improve safety.</p>
> <h2>Photos</h2>
> <table width="100%" border="0" cellpadding="0" cellspacing="0" style="border: 0px !important; margin:0 0 0 0; margin-bottom:0px;">
> <tr>
> <td style="padding:0 0 0 0; border: 0px !important; text-align:center;" width="700"  valign="middle">
> <p><a class="swipebox" id="gal_1" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-1.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="1" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-17-150x150.jpg"></a><a class="swipebox" id="gal_2" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-2.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="2" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-16-150x150.jpg"></a><a class="swipebox" id="gal_3" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-3.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="3" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-150x150.jpg"></a><a class="swipebox" id="gal_4" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-4.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="4" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-3-150x150.jpg"></a><a class="swipebox" id="gal_5" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-5.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="5" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-15-150x150.jpg"></a><a class="swipebox" id="gal_6" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-6.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="6" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-2-150x150.jpg"></a><a class="swipebox" id="gal_7" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-7.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="7" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-10-150x150.jpg"></a><a class="swipebox" id="gal_8" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-8.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="8" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-8-150x150.jpg"></a><a class="swipebox" id="gal_9" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-9.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="9" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-5-150x150.jpg"></a><a class="swipebox" id="gal_10" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-10.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="10" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-14-150x150.jpg"></a><a class="swipebox" id="gal_11" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-11.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="11" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-13-150x150.jpg"></a><a class="swipebox" id="gal_12" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-12.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="12" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-12-150x150.jpg"></a><a class="swipebox" id="gal_13" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-13.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="13" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-11-150x150.jpg"></a><a class="swipebox" id="gal_14" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-14.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="14" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-9-150x150.jpg"></a><a class="swipebox" id="gal_15" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-15.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="15" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-7-150x150.jpg"></a><a class="swipebox" id="gal_16" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-16.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="16" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-6-150x150.jpg"></a><a class="swipebox" id="gal_17" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-17.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="17" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-18-150x150.jpg"></a><a class="swipebox" id="gal_18" title="Tesla Model X 2016 Geneva Motor Show"
> href="/photos/tesla-saves-life-auto-pilot-picture-18.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="18" data-description=""  
> alt=""
> src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-1-150x150.jpg"></a></td>
> </tr>
> </table>
> <p>Via &#8211; <a href="http://www.slate.com/articles/technology/future_tense/2016/08/tesla_says_autopilot_is_saving_lives_should_we_believe_it.html" target="_blank">Slate.com</a></p>
> 


**transformed markup**

> <html>
>   <head>
>     <link rel="canonical" href="https://www.rushlane.com/tesla-saves-life-auto-pilot-12202068.html"/>
>     <meta charset="utf-8"/>
>     <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
>     <meta property="op:generator:version" content="1.3.0"/>
>     <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
>     <meta property="op:generator:application:version" content="2.11"/>
>     <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
>     <meta property="op:generator:transformer:version" content="1.3.0"/>
>     <meta property="op:markup_version" content="v1.0"/>
>     <meta property="fb:use_automatic_ad_placement" content="true"/>
>     <meta property="fb:article_style" content="default"/>
>   </head>
>   <body>
>     <article>
>       <header>
>         <figure>
>           <img src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-15.jpg"/>
>         </figure>
>         <h1>Tesla drives itself to hospital, saves owner's life</h1>
>         <time class="op-published" datetime="2016-08-09T11:24:44+05:30">August 9th, 11:24am</time>
>         <time class="op-modified" datetime="2016-08-09T11:24:44+05:30">August 9th, 11:24am</time>
>         <address><a href="https://www.facebook.com/nithyanandh.karuppaswamy" rel="facebook">Nithyanandh Karuppaswamy</a>Winner of national level automotive quiz competitions, Nithyanandh aka Nithz jumped into the blogosphere right after gaining a degree in Mechanical Engineering. Love for automobiles and an even greater drive to share his knowledge with the automotive community, Nithz is Deputy Editor at RushLane.&#13;
> &#13;
> Email - &lt;a href="mailto:nithyanandh@rushlane.com"&gt;nithyanandh@rushlane.com&lt;/a&gt;</address>
>         <figure class="op-ad">
>           <iframe src="https://www.facebook.com/adnw_request?placement=219861068397808_219864915064090&amp;adtype=banner300x250" width="300" height="250"></iframe>
>         </figure>
>       </header>
>       <p>Even as Tesla’s Auto Pilot driver assist system is under scrutiny following the <a href="https://www.rushlane.com/tesla-model-s-autopilot-fatal-accident-12199962.html">Model S’ fatal crash</a> in the US, the drive assist system has proved its worthiness by saving a Tesla Model X owner from a potentially life-threatening medical emergency.</p>
>       <p>Joshua Neally, a resident of Springfield, Missouri, was driving back from his office when he suffered from pulmonary embolism, a condition of obstruction of blood vessels in the lungs which could potentially be fatal.</p>
>       <p> </p>
>       <p>Neally experienced a piercing pain in his stomach and chest. Instead of parking his car and waiting for the ambulance to arrive, he made a quick decision to leave his fate in the hands of his electric crossover’s Auto Pilot system. He commanded his car’s Auto Pilot mode to take him to the nearest hospital.</p>
>       <p>Roughly 20 miles (32 km) later, the Model X took Neally to a road leading to a hospital’s emergency department. He then parked the car manually and checked himself into the hospital. Now the owner is out of danger but the doctors say that he was lucky to survive the health scare while driving.</p>
>       <p>Obviously, Joshua Neally is extremely happy about his car’s semi-autonomous capabilities that helped him receive medical attention as quick as possible.</p>
>       <p>
>         <b>Also read – <a href="https://www.rushlane.com/man-hacks-tesla-model-s-pokemon-12201806.html">Man hacks Tesla Model S touchscreen to play Pokemon Go</a></b>
>       </p>
>       <p>Reacting to accidents that were caused by alleged malfunctioning of Auto Pilot, Tesla Motors earlier stated that drivers are ultimately responsible for the vehicle’s actions and the system only aims to eliminate driver errors. Neally’s experience adds gravity to Tesla’s claim that the Auto Pilot helps improve safety.</p>
>       <h2>Photos</h2>
>       <figure class="op-interactive">
>         <iframe class="no-margin">
>           <table width="100%" border="0" cellpadding="0" cellspacing="0" style="border: 0px !important; margin:0 0 0 0; margin-bottom:0px;">
>             <tr><td style="padding:0 0 0 0; border: 0px !important; text-align:center;" width="700" valign="middle">
> <p><a class="swipebox" id="gal_1" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-1.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="1" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-17-150x150.jpg"/></a><a class="swipebox" id="gal_2" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-2.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="2" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-16-150x150.jpg"/></a><a class="swipebox" id="gal_3" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-3.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="3" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-4-150x150.jpg"/></a><a class="swipebox" id="gal_4" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-4.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="4" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-3-150x150.jpg"/></a><a class="swipebox" id="gal_5" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-5.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="5" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-15-150x150.jpg"/></a><a class="swipebox" id="gal_6" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-6.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="6" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-2-150x150.jpg"/></a><a class="swipebox" id="gal_7" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-7.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="7" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-10-150x150.jpg"/></a><a class="swipebox" id="gal_8" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-8.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="8" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-8-150x150.jpg"/></a><a class="swipebox" id="gal_9" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-9.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="9" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-5-150x150.jpg"/></a><a class="swipebox" id="gal_10" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-10.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="10" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-14-150x150.jpg"/></a><a class="swipebox" id="gal_11" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-11.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="11" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-13-150x150.jpg"/></a><a class="swipebox" id="gal_12" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-12.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="12" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-12-150x150.jpg"/></a><a class="swipebox" id="gal_13" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-13.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="13" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-11-150x150.jpg"/></a><a class="swipebox" id="gal_14" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-14.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="14" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-9-150x150.jpg"/></a><a class="swipebox" id="gal_15" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-15.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="15" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-7-150x150.jpg"/></a><a class="swipebox" id="gal_16" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-16.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="16" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-6-150x150.jpg"/></a><a class="swipebox" id="gal_17" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-17.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="17" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-18-150x150.jpg"/></a><a class="swipebox" id="gal_18" title="Tesla Model X 2016 Geneva Motor Show" href="/photos/tesla-saves-life-auto-pilot-picture-18.html" target="_blank"><img class="gal-img" data-title="Tesla Model X 2016 Geneva Motor Show" data-gidx="18" data-description="" alt="" src="https://www.rushlane.com/wp-content/uploads/2016/03/Tesla-Model-X-2016-Geneva-Motor-Show-1-150x150.jpg"/></a></p></td>
> </tr>
>           </table>
>         </iframe>
>       </figure>
>       <p>Via – <a href="http://www.slate.com/articles/technology/future_tense/2016/08/tesla_says_autopilot_is_saving_lives_should_we_believe_it.html">Slate.com</a></p>
>     </article>
>   </body>
> </html>

**Comment by everton-rosario** [comment]
Hey @mikemacnn are you using jetpack? 
This is on the Jetpack coverage that we released on [version 3.1](https://github.com/Automattic/facebook-instant-articles-wp/releases/tag/3.1)

Are you still seeing this problem after migrating to the new version?

**Comment by mikemacnn** [comment]
Hi, we see not using jetpack. We see simply using the WordPress plugin.

**Comment by everton-rosario** [comment]
This was just fixed with the PR #205 
Can you double check it, please?

**Comment by mikemacnn** [comment]
Plugin is updated.

Issue not fixed. Just published a new article and shared on facebook.
Cannot see the image which has caption in instant articles

**Comment by everton-rosario** [comment]
@mikemacnn Have you figured out how to solve this?
Can you share with us?

Thanks.

**Comment by ellemcgann** [comment]
Please update, having same issue :(
