### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by CarsonLee27** [Automattic/facebook-instant-articles-wp#397]
# Steps required to reproduce the problem
1. Activate the plugin
2. Publish new article 
3. Error found - HTTP 500 
# Expected Result
- Article published. 
# Actual Result
- HTTP 500, article didn't publish

---

*\* Version Info **
- Plugin version: 3.0.1
- WordPress version: 4.5.3
- PHP version: PHP 5.6.5

*\* Error code **

`PHP message: PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Facebook\InstantArticles\Transformer\Rules\InteractiveInsideParagraphRule does not exist' in....`

Stack trace:

```
#0 /srv/www/xxx.com/public_html/releases/28/wp-content/plugins/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Transformer/Transformer.php(224): ReflectionMethod->__construct('Facebook\\Instan...', 'creat$
#1 /srv/www/xxx.com/public_html/releases/28/wp-content/plugins/facebook-instant-articles-wp/class-instant-articles-post.php(603): Facebook\InstantArticles\Transformer\Transformer->loadRules('{\n    "rules":\n...')
#2 /srv/www/xxx.com/public_html/releases/28/wp-content/plugins/facebook-instant-articles-wp/class-instant-ar" while reading response header from upstream, client: 162.158.26.84, server: tantannews.com, request: "POST /wp-admin/post.php HTTP/1.1", upstream: "fastcg$
```

**Comment by ivcreative** [comment]
I am having the same issue here 

[Tue Aug 23 10:52:00.170220 2016] [:error] [pid 17821] [client 173.233.48.26:44790] PHP Fatal error:  Class 'DOMDocument' not found in /xxxx/xxxx/html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 623, referer: http://xxxxxxxxxxxxxx.com/wp-admin/post.php?post=1274&action=edit

**Comment by diegoquinteiro** [comment]
This should be fixed on the latest version. Please re-open if it persists after updating.

Thank you,
Diego

**Comment by schankam** [comment]
I just installed the plugin, reproduce the exact steps here, got the same error message... Apparently it is not fixed yet
